name: CI/CD for Main Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home1/medha/public_html/TN_INST/  # Change this to your cPanel directory
          local-dir: /
